program main
 #if _OPENACC
      use openacc
 #endif

 integer :: DEVICENUM

 #ifdef _OPENACC
     NGPUS   =   ACC_GET_NUM_DEVICES(ACC_DEVICE_NVIDIA)
     !---CHOOSE DEVICE TO USE BY THIS RANK
     !DEVICENUM   =   MOD(MPI_RANK,NGPUS)
     DEVICENUM   =  0
     CALL ACC_SET_DEVICE_NUM(DEVICENUM,ACC_DEVICE_NVIDIA)
     !---CALL ACC_INIT AFTER ACC_SET_DEVICE_NUM TO AVOID MULTIPLE CONTEXTS ON DEVICE 0 IN MULTI GPU SYSTEMS
     CALL ACC_INIT(ACC_DEVICE_NVIDIA)
 #endif
end program
